name: Ensure notebooks are clean

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  clean-notebooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1